### ISSUE TITLE
Fail to find arguments using ccache

### ISSUE THREAD

**Issue by ismaelgv** [roxma/ncm-clang#1]
`ncm-lang` fails to find completion arguments when you use `ccache` on compile_commands.json. In my case, I am generating compile_commands.json with Meson build system that automatically detects `ccache`.

Example compile_commands.json:
```json
[
  {
    "directory": "/home/ismael/Repos/timesh/build",
    "command": "ccache c++  -Itest@exe -I. -I.. -I../include -Isrc -I../src -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O3 -frounding-math -DCGAL_NDEBUG -MMD -MQ 'test@exe/main.cpp.o' -MF 'test@exe/main.cpp.o.d' -o 'test@exe/main.cpp.o' -c ../src/main.cpp",
    "file": "../src/main.cpp"
  }
]
```

Log generated by `ncm-clang`:
```
2017-09-30 17:53:14,107 [ERROR @ ncm_clang.py:args_from_cmake:28] 832 - Failed finding args from /home/user/repos/test/build/compile_commands.json for /home/user/repos/test/src/main.cpp                  
```
If you remove 'ccache' string from "command" in compile_commands.json, everything works fine.

**Comment by ismaelgv** [comment]
After the last commit completion is working more or less but there are new errors on the log:
```
2017-10-01 11:47:54,325 [ERROR @ ncm_clang.py:args_from_cmake:40] 20424 - Exception processing {'directory': '/home/user/repos/test/build', 'command': "ccache c++  -Itest@exe -I. -I.. -I../include -Isrc -I../src -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O3 -frounding-math -DCGAL_NDEBUG -MMD -MQ 'test@exe/main.cpp.o' -MF 'test@exe/main.cpp.o.d' -
o 'test@exe/main.cpp.o' -c ../src/main.cpp", 'file': '../src/main.cpp'}
Traceback (most recent call last):
  File "/home/user/.vim/plugged/ncm-clang/pythonx/ncm_clang.py", line 35, in args_from_cmake
    if samefile(cmd['file'], filepath):
  File "/usr/lib/python3.6/genericpath.py", line 96, in samefile
    s1 = os.stat(f1)
FileNotFoundError: [Errno 2] No such file or directory: '../src/main.cpp'
2017-10-01 11:47:54,328 [ERROR @ ncm_clang.py:args_from_cmake:40] 20424 - Exception processing {'directory': '/home/user/repos/test/build', 'command': "ccache c++  -Itest@exe -I. -I.. -I../include -Isrc -I../src -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O3 -frounding-math -DCGAL_NDEBUG -MMD -MQ 'test@exe/config.cpp.o' -MF 'test@exe/config.cpp.o.d' -o 'test@exe/config.cpp.o' -c ../src/config.cpp", 'file': '../src/config.cpp'}
Traceback (most recent call last):
  File "/home/user/.vim/plugged/ncm-clang/pythonx/ncm_clang.py", line 35, in args_from_cmake
    if samefile(cmd['file'], filepath):
  File "/usr/lib/python3.6/genericpath.py", line 96, in samefile
    s1 = os.stat(f1)
```

Should I open a new issue?

**Comment by roxma** [comment]
I've pushed another update.

**Comment by ismaelgv** [comment]
It seems fixed now, thanks!
